name: Build and Deploy Docs

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches: ["tech_debt/AIC-5935"]

jobs:
  build-deploy-docs:
    runs-on: ubuntu-latest
    env:
      IRIS_ENV: SERVER

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for pushing to gh-pages

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Install package and build dependencies
        run: |
          set -e
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements/dev.txt

      - name: Build docs (Makefile)
        run: make build-docs

      - name: Set up gh-pages worktree
        run: |
          git fetch origin gh-pages:gh-pages
          git worktree add gh-pages-dir gh-pages

      - name: Copy docs to gh-pages worktree
        run: |
          rm -rf gh-pages-dir/*
          cp -r docs/build/html/* gh-pages-dir/
          cd gh-pages-dir
          git add .
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Automated docs update" || echo "No changes to commit"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          path: gh-pages-dir
          branch: docs-update
          title: "Automated docs update"
          body: "This PR updates the documentation on gh-pages branch."
          base: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Commit documentation changes
      #   run: |
      #     set -e
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git config --global user.name "github-actions[bot]"
      #     git fetch origin gh-pages:gh-pages
      #     git checkout gh-pages
      #     git pull origin gh-pages
      #     git checkout -b docs-update
      #     git add ./docs/build/html
      #     git commit -m "Automated docs update"

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v7
      #   with:
      #     branch: docs-update
      #     title: "Automated docs update"
      #     body: "This PR updates the documentation on gh-pages branch."
      #     base: gh-pages
      #     token: ${{ secrets.GITHUB_TOKEN }}

